apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-admin
spec:
  replicas: {{ .Values.deployment.replicasAdmin }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-admin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-admin
    spec:
      containers:
      - name: {{ .Release.Name }}-admin
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-db
        - configMapRef:
            name: {{ .Release.Name }}-general
        env:
          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-admin
                key: password
          - name: DB_HOST
            value: {{ include "mariadb.primary.fullname" .Subcharts.mariadb }}
          - name: DB_PORT
            value: {{ coalesce .Values.mariadb.primary.service.ports.mysql .Values.mariadb.primary.service.port | quote }}
          - name: MARIADB_DATABASE
            value: {{ .Values.mariadb.auth.database | quote }}
          - name: MARIADB_USER
            value: {{ .Values.mariadb.auth.username | quote }}
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mariadb.secretName" .Subcharts.mariadb }}
                key: mariadb-root-password
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mariadb.secretName" .Subcharts.mariadb }}
                key: mariadb-password
        volumeMounts:
        - name: certificates-volume
          mountPath: /home/certificates
        - name: gromox-services-volume
          mountPath: /home/gromox-services
        - name: admin-plugins-volume
          mountPath: /home/plugins
        - name: admin-links-volume
          mountPath: /home/links
        - name: nginx-volume
          mountPath: /home/nginx
      volumes:
      - name: certificates-volume
        secret:
          secretName: {{ .Release.Name }}-cert-tls
      - name: admin-plugins-volume
        configMap:
          name: {{ .Release.Name }}-admin-plugins
          defaultMode: 0777 
      - name: admin-links-volume
        configMap:
          name: {{ .Release.Name }}-admin-links
          defaultMode: 0777
      - name: gromox-services-volume
        configMap:
          name: {{ .Release.Name }}-services
      - name: nginx-volume
        configMap:
          name: {{ .Release.Name }}-nginx
